services:
  - type: web
    name: beatoven
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BEATOVEN_ENV
        sync: false
      - key: BEATOVEN_HOST
        sync: false
      - key: BEATOVEN_PORT
        sync: false
      - key: BEATOVEN_WORKERS
        sync: false
      - key: PORT
        sync: false
      - key: LOG_LEVEL
        sync: false
